apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-data-service
  labels:
    name: get-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: get-data-service
  template:
    metadata:
      labels:
        name: get-data-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "get-data-service"
        dapr.io/port: "80"
    spec:
      containers:
      - name: get-data-service
        image: IMG
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: get-data-service
  name: get-data-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: get-data-service
  type: LoadBalancer