apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-checker
  labels:
    name: email-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: email-checker
  template:
    metadata:
      labels:
        name: email-checker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "email-checker"
        dapr.io/port: "8080"
    spec:
      containers:
      - name: email-checker
        image: IMG
        env:
          - name: VENTUS_EMAIL_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: email-credentials 
                 key: ventus-email-password
          - name: NO_REPLY_EMAIL
            valueFrom:
               secretKeyRef:
                 name: email-credentials 
                 key: no-reply-email     
        ports:
        - containerPort: 8080
        imagePullPolicy: Always